# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nix/store/r9941n32g4wyvggz2703dlplbdq8a6rd-cmake-4.1.2/bin/cmake

# The command to remove a file.
RM = /nix/store/r9941n32g4wyvggz2703dlplbdq8a6rd-cmake-4.1.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/foksik/Projects/coreUtils

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/foksik/Projects/coreUtils

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/nix/store/r9941n32g4wyvggz2703dlplbdq8a6rd-cmake-4.1.2/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/nix/store/r9941n32g4wyvggz2703dlplbdq8a6rd-cmake-4.1.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/foksik/Projects/coreUtils/CMakeFiles /home/foksik/Projects/coreUtils//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/foksik/Projects/coreUtils/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named foolisbox

# Build rule for target.
foolisbox: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 foolisbox
.PHONY : foolisbox

# fast build rule for target.
foolisbox/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/foolisbox.dir/build.make CMakeFiles/foolisbox.dir/build
.PHONY : foolisbox/fast

src/entry.o: src/entry.asm.o
.PHONY : src/entry.o

# target to build an object file
src/entry.asm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/foolisbox.dir/build.make CMakeFiles/foolisbox.dir/src/entry.asm.o
.PHONY : src/entry.asm.o

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/foolisbox.dir/build.make CMakeFiles/foolisbox.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/foolisbox.dir/build.make CMakeFiles/foolisbox.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/foolisbox.dir/build.make CMakeFiles/foolisbox.dir/src/main.c.s
.PHONY : src/main.c.s

src/utils/cat.o: src/utils/cat.c.o
.PHONY : src/utils/cat.o

# target to build an object file
src/utils/cat.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/foolisbox.dir/build.make CMakeFiles/foolisbox.dir/src/utils/cat.c.o
.PHONY : src/utils/cat.c.o

src/utils/cat.i: src/utils/cat.c.i
.PHONY : src/utils/cat.i

# target to preprocess a source file
src/utils/cat.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/foolisbox.dir/build.make CMakeFiles/foolisbox.dir/src/utils/cat.c.i
.PHONY : src/utils/cat.c.i

src/utils/cat.s: src/utils/cat.c.s
.PHONY : src/utils/cat.s

# target to generate assembly for a file
src/utils/cat.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/foolisbox.dir/build.make CMakeFiles/foolisbox.dir/src/utils/cat.c.s
.PHONY : src/utils/cat.c.s

src/utils/cp.o: src/utils/cp.c.o
.PHONY : src/utils/cp.o

# target to build an object file
src/utils/cp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/foolisbox.dir/build.make CMakeFiles/foolisbox.dir/src/utils/cp.c.o
.PHONY : src/utils/cp.c.o

src/utils/cp.i: src/utils/cp.c.i
.PHONY : src/utils/cp.i

# target to preprocess a source file
src/utils/cp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/foolisbox.dir/build.make CMakeFiles/foolisbox.dir/src/utils/cp.c.i
.PHONY : src/utils/cp.c.i

src/utils/cp.s: src/utils/cp.c.s
.PHONY : src/utils/cp.s

# target to generate assembly for a file
src/utils/cp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/foolisbox.dir/build.make CMakeFiles/foolisbox.dir/src/utils/cp.c.s
.PHONY : src/utils/cp.c.s

src/utils/echo.o: src/utils/echo.c.o
.PHONY : src/utils/echo.o

# target to build an object file
src/utils/echo.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/foolisbox.dir/build.make CMakeFiles/foolisbox.dir/src/utils/echo.c.o
.PHONY : src/utils/echo.c.o

src/utils/echo.i: src/utils/echo.c.i
.PHONY : src/utils/echo.i

# target to preprocess a source file
src/utils/echo.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/foolisbox.dir/build.make CMakeFiles/foolisbox.dir/src/utils/echo.c.i
.PHONY : src/utils/echo.c.i

src/utils/echo.s: src/utils/echo.c.s
.PHONY : src/utils/echo.s

# target to generate assembly for a file
src/utils/echo.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/foolisbox.dir/build.make CMakeFiles/foolisbox.dir/src/utils/echo.c.s
.PHONY : src/utils/echo.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... foolisbox"
	@echo "... src/entry.o"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils/cat.o"
	@echo "... src/utils/cat.i"
	@echo "... src/utils/cat.s"
	@echo "... src/utils/cp.o"
	@echo "... src/utils/cp.i"
	@echo "... src/utils/cp.s"
	@echo "... src/utils/echo.o"
	@echo "... src/utils/echo.i"
	@echo "... src/utils/echo.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

